-- CreateEnum
CREATE TYPE "CoachTone" AS ENUM ('DRILL_SERGEANT', 'SUPPORTIVE_FRIEND', 'NEUTRAL_ANALYST');

-- AlterTable
ALTER TABLE "Commitment"
ADD COLUMN "coachTone" "CoachTone" NOT NULL DEFAULT 'SUPPORTIVE_FRIEND';
